[package]
name = "123marble-rbx/rbx-rankdb"
version = "2.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT OR Apache-2.0"
exclude = ["benchmark", "build", "testRunner.server.lua", "src/tests"]

[dependencies]
testez = "roblox/testez@0.4.1"

[dev-dependencies]
